package se.droogies.bromaniac.adventofcode15.day5;

import java.util.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {

       /* List<String> foo = Arrays.asList("ugknbfddgicrmopn", "aaa", "jchzalrnumimnmhp"
                , "haegwjzuvuyypxyu"
                , "dvszwmarrgswjxmb");

        foo.stream()
                .filter(s -> s.contains("aa"))
                .filter(s -> s.contains("a"))
                .filter(s -> ! s.contains("ab"))
                .forEach(System.out::println);*/
       String foo = "ugknbfddgicrmopn";
       for(char c: foo.toCharArray()) {

       }

    }

}
